-- ── Auth schema & users table ────────────────────────────────────────────────
CREATE SCHEMA IF NOT EXISTS auth;

CREATE TABLE IF NOT EXISTS auth.users (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username     VARCHAR(100) NOT NULL UNIQUE,
    email        VARCHAR(255),
    password_hash VARCHAR(255),           -- BCrypt hash; NULL for SSO-only users
    role         VARCHAR(50)  NOT NULL DEFAULT 'VIEWER',
    tenant_id    VARCHAR(100) NOT NULL DEFAULT 'tenant-1',
    tenant_name  VARCHAR(255)          DEFAULT 'Primary Workspace',
    -- SSO readiness columns
    sso_provider VARCHAR(50),            -- e.g. 'OKTA', 'AZURE_AD'; NULL = local auth
    sso_subject  VARCHAR(255),           -- provider's unique subject/ID
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS auth.users_audit (
    audit_id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    action_type VARCHAR(10)  NOT NULL,
    changed_by  VARCHAR(255),
    changed_at  TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    row_data    JSONB
);

-- audit trigger
DROP TRIGGER IF EXISTS trg_users_audit ON auth.users;
CREATE TRIGGER trg_users_audit
AFTER INSERT OR UPDATE OR DELETE ON auth.users
FOR EACH ROW EXECUTE FUNCTION audit_log_trigger_func();

-- ── Seed default users ──────────────────────────────────────────────────────
-- Hashes generated by BCryptPasswordEncoder(cost=10) — verified real hashes
-- admin/admin123  analyst/analyst123  viewer/viewer123
INSERT INTO auth.users (username, email, password_hash, role, tenant_id, tenant_name)
VALUES
  ('admin',   'admin@mcp.local',   '$2a$10$W9jPu.BKQ7IFJoaE86m3Sun.d4qqKfD4gRd24EikE6Cjp5xbkh3f.', 'ADMIN',   'tenant-1', 'Primary Workspace'),
  ('analyst', 'analyst@mcp.local', '$2a$10$6XMZsalDITiFwWHX.2RlwOaLpFwAKAtUeoUvn83dVcr6aNuXO.JF6', 'ANALYST', 'tenant-1', 'Primary Workspace'),
  ('viewer',  'viewer@mcp.local',  '$2a$10$1e0Oof8hQepG6ceXkfLWOua2i0q33wMeFYYXcKr2xS669C1R3Vrr6', 'VIEWER',  'tenant-1', 'Primary Workspace')
ON CONFLICT (username) DO UPDATE
  SET password_hash = EXCLUDED.password_hash,
      role          = EXCLUDED.role,
      tenant_id     = EXCLUDED.tenant_id,
      tenant_name   = EXCLUDED.tenant_name;
